### ISSUE TITLE
Handle expiration date or duration lifetime of cookies

### ISSUE THREAD

**Issue by Daksh14** [OctaneWeb/Octane#15]
**Is your feature request related to a problem? Please describe.**
Cookies are not tied to a expiration date/lifetime 

**Describe the solution you'd like**
Ask the user for a `Duration` and form a expiration date from it and send it with `Set-Cookie` 

**Describe alternatives you've considered**
None

**Describe any implementations if you have one**
None

**Comment by somebody1234** [comment]
I really feel like this might not be a great idea before Octane has a `Cookie` struct.  
Also maaaaybe possibly a builder pattern would be nice for this, just a thought

**Comment by Daksh14** [comment]
Closed by #31 as we are now using cookie-rs
